# ~~~
# Copyright (c) 2025-2026 The Khronos Group Inc.
# Copyright (c) 2025-2026 RasterGrid Kft.
#
# SPDX-License-Identifier: Apache-2.0
# ~~~
version = 1
SPDX-PackageName = "Vulkan SC SDK"
SPDX-PackageSupplier = "The Khronos Group, Inc."
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/VulkanSC-SDK"

[[annotations]]
path = [
# JSON can't have SPDX-style comments
    "CMakePresets.json",
# assets can't have SPDX-style comments
    "installer/resources/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 The Khronos Group, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
# Markdown can't have SPDX-style comments
    "**.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 The Khronos Group, Inc."
SPDX-License-Identifier = "CC-BY-4.0"
