# Copyright (c) 2025 The Khronos Group Inc.
# Copyright (c) 2025 RasterGrid Kft.
#
# SPDX-License-Identifier: Apache-2.0

name: Presubmit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  github-release:
    name: GitHub Release
    runs-on: ${{matrix.OS}}
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        include:
          - OS: windows-2022
            WORKFLOW: msbuild-ci-windows
            PACKAGE: ZIP
          - OS: ubuntu-22.04
            WORKFLOW: ninja-ci-linux
            PACKAGE: TGZ
    steps:
    - name: Checkout VulkanSC-SDK
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: REUSE Compliance Check
      if: ${{ contains(matrix.WORKFLOW, 'linux') }}
      uses: fsfe/reuse-action@v5

    - name: Get latest ninja
      if: ${{ contains(matrix.WORKFLOW, 'ninja') }}
      uses: urkle/action-get-ninja@v1

    - name: Get windowing system packages
      if: ${{ contains(matrix.WORKFLOW, 'linux') }}
      run: |
        sudo apt-get -qq update
        sudo apt install --yes cmake git gcc g++ python3 pkg-config libx11-xcb-dev libwayland-dev xorg-dev

    - name: Configure
      run: cmake --preset ${{matrix.WORKFLOW}}

    - name: Build
      run: cmake --build --preset ${{matrix.WORKFLOW}}-release-install

    - name: Test
      run: ctest --preset ${{matrix.WORKFLOW}}-release

    - name: Package
      run: cpack -G ${{matrix.PACKAGE}} -C Release --config ./build/CPackConfig.cmake -B ./package
